repos:
  - repo: local
    hooks:
      - id: checkstyle
        name: Checkstyle
        entry: ./gradlew checkstyleMain checkstyleTest -q
        language: system
        types: [java]
        pass_filenames: false

      - id: spotbugs
        name: SpotBugs
        entry: ./gradlew spotbugsMain spotbugsTest -q
        language: system
        types: [java]
        pass_filenames: false

      - id: pmd
        name: PMD
        entry: ./gradlew pmdMain pmdTest -q
        language: system
        types: [java]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
